### ISSUE TITLE
Example upload doesn't work on Zapier env

### ISSUE THREAD

**Issue by IGimpels** [zapier/zapier-platform-example-app-files#4] opened 2017-04-20 09:42 UTC
I pushed the example into Zapier and create a flow where the file should be uploaded to the example app (f.e: Google Drive -> Example app) and I got the following result:
>
  Starting POST request to https://zapier.webscript.io/platform-example-app/upload
  Received 400 code from https://zapier.webscript.io/platform-example-app/upload after 218ms
  Received content "File is required"
  Cannot read property 'id' of undefined

When I tested upload with my server using your example, I have got the request where the url to file instead of file body, like this:

----------------------------518771434464875223249565
Content-Disposition: form-data; name="filename"

Jellyfish.jpg
----------------------------518771434464875223249565
Content-Disposition: form-data; name="file"

https://zapier.com/engine/hydrate/2144530/.eJxtkMtqwzAQRf9Fi67SSJZlNzKEQqAhfZBCG7o1tiTLjmTL0aNpGvrvlaDLDrOYezgMzFzBMDnfTEzUAwcVRvQuQ4guQDcIzeupGQWoYtACLADrBVO1EpcoZoQUOYrMTF5MvvaXOZn7qKlzY6UD1RUEqyPrvZ9dBSE37BbJ1HFyS2mM1CI4Yf92LJkZk-SgEyxY4RjkvuWqs3OP8qZXROl2PnV0yIL5bJULCNrQIzJ4102sMcfSyBUZnSc-HLESeadgRigmOMcoFcwwWpV5scooKYuiLEhB6f8Qbb5KevjYvOyed4_vWO9b9XY6bLffrw_qXqy5OU_aNPxG8rW3IX2nM3ZsfLz3OMsY_eB1-siT0PrSDa5fJv7z8wsUwnbD:1d05G5:Zd2wccCGUDwX9ELa9A90og756rA/
----------------------------518771434464875223249565

...

**Comment by BrunoBernardino** [comment] 2017-06-02 10:28
Hi @IGimpels I'm so sorry for the late reply here! This is a problem in how we've given you the example app.

This is a duplicate of https://github.com/zapier/zapier-platform-core/issues/35 and is being solved in the example app by https://github.com/zapier/zapier-platform-example-app-files/pull/5

**Closed by BrunoBernardino** 2017-06-02 10:28 UTC
